version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  rails:
    build: .
    image: idea-memo-board/service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=postgresql://user:password@devdb
      - APP_DOMAIN=http://localhost:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/service
